import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '@/app/globals.css'

import Layout from '@/app/components/templates/Layout'
import { HomePage } from '@/app/components/templates/HomePage'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Home() {
  return (
    <Layout>
      <HomePage locale="en" />
    </Layout>
  )
}
